[book]
title = "zwasm"
description = "A standalone WebAssembly runtime written in Zig"
authors = ["zwasm contributors"]
language = "en"
src = "src"

[build]
build-dir = "../../docs/book/en"

[output.html]
git-repository-url = "https://github.com/clojurewasm/zwasm"
additional-css = ["custom.css"]
additional-js = ["lang-switcher.js"]
